#!/bin/sh

# go to main dir
cd "$(git rev-parse --show-toplevel)"

#update open-wallet.io
curl -s http://open-wallet.io/update

# compile css after pull
grunt sass
RETVAL=$?

if [ $RETVAL -ne 0 ]
then
  exit 1
fi
